[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
rusqlite = { version = "0.32.0", features = ["bundled"] }
prettytable-rs = "^0.10"